version: 0.0
os: linux
hooks:
  ApplicationStop:
    - location: code-deploy/stop-java.sh
      runas: root
  BeforeInstall:
    - location: code-deploy/fix-java.sh
      runas: root
  ApplicationStart:
    - location: code-deploy/run.sh
